### ISSUE TITLE
Windows 95 Build 499 Doesn't work/install

### ISSUE THREAD

**Issue by jdmulloy** [jeffpar/pcjs#13]
Hi,

I tried to install Windows 95 build 499 on this page https://www.pcjs.org/software/pcx86/sys/windows/win95/4.00.499/ and the installed complains about a lack of space. The first issue is that it boots DOS 3.x which can only create and format a 32MB partition for C:. Then using the 6.22 install/boot disk to run fdisk and format the disk is still slightly too small for the installer. Can you make the disk bigger and make it boot from a newer DOS floppy?

Also is there and easy way to customize the machines on the webpage? Like if I want a bigger disk or more RAM. So far it seems the Windows 95 system is the biggest and I can't get it to reboot to a floppy for some reason.

**Comment by IAW9927** [comment]
Install DOS 6.22 or DOS 6 and type “dblspace” or “drvspace” to make the hard disk for 32-49MB around 60/70 which is big enough!

**Comment by jeffpar** [comment]
COMPAQ machines with 47Mb hard drives were using the wrong default boot diskette.  Those have been changed to use COMPAQ MS-DOS 3.31 now, which supports > 32Mb partitions.  However, for this particular page, I override that default with an MS-DOS 5.00 diskette, because that makes the Windows 95 setup process happier.  I've summarized the installation steps at the top of the page now.  See 7501da51613bb4b92f3f0901d68b1daa6feb1d27.

There are some machine settings you can override with URL parameters; for example, this [machine](https://www.pcjs.org/machines/pcx86/ibm/5150/cga/) can be reconfigured with 256Kb by adding "sizeRAM=256" to the [URL](https://www.pcjs.org/machines/pcx86/ibm/5150/cga/?sizeRAM=256).  However, I don't have a definitive list of those parameters right now.

**Comment by qodeos** [comment]
#69
Uses Build 499
