### ISSUE TITLE
(WIP) Maybe port to WebAssembly?

### ISSUE THREAD

**Issue by j8srv32** [jeffpar/pcjs#49]
We might need to port this to WebAssembly for better performance.

**Comment by randompersononinternet69** [comment]
Well, this would remove old support for browsers that don't support WebAssembly.

**Comment by jeffpar** [comment]
Which machines need better performance?

**Comment by jeffpar** [comment]
Closing this as "won't fix" since PCjs was created to simulate old machines (nothing newer than the Intel 80386) running old operating systems (nothing newer than Windows 95) running at their **original speed**, and it can do that fine as-is.  There are plenty of other emulators out there that can be (and have been) ported to the web using WebAssembly if you want more than that.

In addition, converting the current Javascript source code to WASM probably wouldn't result in any significant improvements, since browsers are already very efficient at converting Javascript to native code.  And porting all the source code to C++ or Rust would be a lot of work that wouldn't solve any problems or add any useful features.  But, if someone else wants to give those things a try, I'll be happy to check out the results.
