### ISSUE TITLE
ERROR `/api/v1/dump' not found.

### ISSUE THREAD

**Issue by AndersBNielsen** [jeffpar/pcjs#63]
Running pcjs locally. 

When trying to load a ROM then backend reports 
ERROR `/api/v1/dump' not found.

The debugger reports:
ROMx86: Unable to load system ROM (error 404: http://localhost:4000/api/v1/dump?file=/machines/pcx86/ibm/5160/rom/fdc/floppy_bios.bin&format=bytes&decimal=true)
(I created the fdc/floppy_bios.bin file)

I got the impression conversion to json was automatic but seeing this, it looks like that feature is broken.

**Comment by jeffpar** [comment]
That API was a feature of [PCjs v1](https://github.com/jeffpar/pcjs.v1) when PCjs ran from a node.js web server.  PCjs v2 doesn't support any server APIs, so that it can be hosted with GitHub Pages.  This means that any ROMs hosted by the server must be converted to JSON first.  The PCx86 app could be modified to load binary files as well as JSON files, but it's not a feature I've needed.  To convert a binary file to JSON, see the [filedump](https://github.com/jeffpar/pcjs/tree/master/tools/old/filedump) utility.  There's some documentation for it buried in the [code](https://github.com/jeffpar/pcjs/blob/a110aae1bfd05cfbdcd0358b0c21289d06d32d24/tools/old/filedump/lib/filedump.js#L124).

**Comment by AndersBNielsen** [comment]
Thank you! 
That makes sense. I found the utility and successfully converted some code while waiting.

Took some digging to find it, had to install a fresh node.js and resolve a dependency of mkdirp but it did the job perfectly.

I guess most people could find it too with some digging. And most people won't need it.
